version: '3.8'
services:
  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=noichu
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=noichu_user
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"
