services:
  - type: web
    name: mysql-db
    env: docker
    repo: https://github.com/BenSuqw123/noichu
    plan: free
    envVars:
      - key: MYSQL_DATABASE
        value: noichu
      - key: MYSQL_ROOT_PASSWORD
        value: 123456
      - key: MYSQL_USER
        value: noichu_user
      - key: MYSQL_PASSWORD
        value: 123456